# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161130_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.TextField(),
        ),
    ]
