# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_todo_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.List'),
        ),
    ]
